アラートの実装
SakaueYae/Yae-frontend-basic-2022-todoapp pull request #11
Opened 2023-04-06 14:52 UTC by SakaueYae

レビューお願いします！🙇‍♀️
https://sakaueyae.github.io/Yae-frontend-basic-2022-todoapp/

2023-04-07 15:08 UTC, KEISUKE0293 reviewed
現状アラートがフェードイン,アウトで表示できていないのでそこの修正をお願いします！

2023-04-07 15:08 UTC, KEISUKE0293 commented on src/contexts/alert_handler.jsx
> +  };
ここの部分多分prettier機能していないと思うので一応下の'contextValue'と同じような形になるようお願いします！

2023-04-09 15:38 UTC, KEISUKE0293 reviewed
１点だけコメントしました！

2023-04-09 15:38 UTC, KEISUKE0293 commented on src/contexts/alert_handler.jsx
> +      errorText: alertState.erroText,
ここの部分がタイプミス？あるので修正してください！
※アラートがフェードアウトするとき一瞬だけテキストが消えていたのですがおそらくこれが原因です。また、今回は途中でテキスト変更がないのでここでテキストをわざわざ更新する必要もないかなと感じます。

2023-04-10 02:41 UTC, higashiji2000 requested changes
keisukeさんに指摘していただいたところだけ修正お願いします！

2023-04-10 02:41 UTC, higashiji2000 commented on src/contexts/alert_handler.jsx
> +    closeAlert: closeAlert,
```suggestion
    setAlert,
    closeAlert,
```
プロパティ名と値の変数名が同じ場合はこのように書くこともできます！

2023-04-12 07:08 UTC, Higashiji approved these changes
LGTMです 🎉

2023-04-12 11:29 UTC, merged